package backend












































































}	defer resp.Body.Close()	}		return		log.Printf("Failed to send metrics: %v", err)	if err != nil {	resp, err := http.Post(balancerURL+"/receive-metrics", "application/json", bytes.NewReader(body))	body, _ := json.Marshal(payload)	}		"total_on_queue": atomic.LoadInt64(&queueSize),		"vmbw":           0.0,		"ifs":            0,		"ip_vm":          myIP,		"tli":            0,		"ttj":            0.0,		"NumberTask":     1,		"Pemips":         0,		"Penumj":         0,		"TimeStartSend":  time.Now().UnixMilli(), // Approximate		"TimeDoneTask":   doneTimeMs,	payload := map[string]interface{}{func sendMetrics(doneTimeMs int64) {}	go sendMetrics(doneTime)	doneTime := time.Since(start).Milliseconds()	// Send feedback asynchronously	w.Write([]byte("Processed"))	w.WriteHeader(http.StatusOK)	time.Sleep(100 * time.Millisecond)	// Simulate work	defer atomic.AddInt64(&queueSize, -1)	atomic.AddInt64(&queueSize, 1)	start := time.Now()func handleRequest(w http.ResponseWriter, r *http.Request) {}	log.Fatal(http.ListenAndServe(":"+port, nil))	log.Printf("Backend listening on :%s, reporting to %s as %s", port, balancerURL, myIP)	http.HandleFunc("/TestHTTP3", handleRequest)	}		port = v	if v := os.Getenv("PORT"); v != "" {	port := "8081"	}		myIP = v	if v := os.Getenv("MY_IP"); v != "" {	}		balancerURL = v	if v := os.Getenv("BALANCER_URL"); v != "" {func main() {)	queueSize   int64	myIP        = "localhost"	balancerURL = "http://localhost:8084"var ()	"time"	"sync/atomic"	"os"	"net/http"	"log"	"fmt"	"encoding/json"	"bytes"import (package main