apiVersion: v1
kind: Namespace
metadata:
  name: backend-ns

---
apiVersion: v1
kind: Namespace
metadata:
  name: backend2-ns

---
apiVersion: v1
kind: Namespace
metadata:
  name: backend3-ns

---
apiVersion: v1
kind: Namespace
metadata:
  name: backend4-ns

---
apiVersion: v1
kind: Namespace
metadata:
  name: backend5-ns

---
apiVersion: v1
kind: Namespace
metadata:
  name: backend6-ns

---
apiVersion: v1
kind: Namespace
metadata:
  name: backend7-ns

---
apiVersion: v1
kind: Namespace
metadata:
  name: backend8-ns

---
apiVersion: v1
kind: Namespace
metadata:
  name: backend9-ns

---
apiVersion: v1
kind: Namespace
metadata:
  name: backend10-ns
